language: java
jdk: openjdk8
before_install:
 - chmod +x gradlew
deploy:
  provider: releases
  api_key: "c30e383d2c79501b9a80fe981ef9663f780e42b7"
  file: "ipwhitelist.jar"
  skip_cleanup: true
  on:
    repo: austin4195/IpWhitelist
    tags: true
